apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: starlight-staging-ingress
  namespace: starlight-staging
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: ssg.ilhaeng.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: starlight-staging-service  # Service의 이름!
                port:
                  number: 80
