apiVersion: apps/v1
kind: Deployment
metadata:
  name: starlight-production
  namespace: starlight-production
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: starlight-production
  template:
    metadata:
      labels:
        app: starlight-production
    spec:
      containers:
        - name: starlight
          image: leosunghojung/startuplight-be:742104d
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
