apiVersion: v1
kind: Service
metadata:
  name: starlight-production-service
  namespace: starlight-production
spec:
  selector:
    app: starlight-production
  ports:
    - port: 80
      targetPort: 8080
